### PR TITLE
Quick Settings

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**

### CODE REVIEW

**Comment by LakshyaTaneja** [comment]
The implementation I am using has ability to set custom number of QS rows and columns from the QS menu itself. No definite need of this I guess.

**Comment by Hikari-no-Tenshi** [comment]
I thought that it's would be better to have all custom settings in one place.

**Comment by LakshyaTaneja** [comment]
I still say we don't need to put extra code for the same stuff which is working fine, instead add new stuff to the code.

**Comment by Hikari-no-Tenshi** [comment]
OK

**Comment by LakshyaTaneja** [comment]
Thanks for Understanding. :)

**Pull request closed without merging**
